### PR TITLE
Added Sunrise links

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by oscarotero** [comment]
Hi. thanks for the contribution. In PSR-7 I'd preffer to provide direct links instead a search result. Something like this:

```md
- sunrise: 
  - [Stream](https://github.com/sunrise-php/stream)
  - [Uri](https://github.com/sunrise-php/uri)
  - etc...
```

Thanks!

**Comment by fenric** [comment]
> Hi. thanks for the contribution. In PSR-7 I'd preffer to provide direct links instead a search result. Something like this:
> 
> ```lisp
> - sunrise: 
>   - [Stream](https://github.com/sunrise-php/stream)
>   - [Uri](https://github.com/sunrise-php/uri)
>   - etc...
> ```
> 
> Thanks!

Thank you, completed :)

**Comment by oscarotero** [comment]
Opps, why did you add the sunrise/http-router to the Dispatchers list instead Routers? Can you fix this, please?

**Comment by fenric** [comment]
> Opps, why did you add the sunrise/http-router to the Dispatchers list instead Routers? Can you fix this, please?

Yes of course. The "sunrise/http-router" is not middleware, it's the server request handler... But I can add it to the Routers section...

**Comment by fenric** [comment]
> Opps, why did you add the sunrise/http-router to the Dispatchers list instead Routers? Can you fix this, please?

**Pull request creation failed. Validation failed: You can't perform that action at this time.**

**Pull request merged**
